---
root: true
extends:
  - airbnb-base
  - plugin:import/errors
  - prettier
plugins:
  - no-not-accumulator-reassign
  - prettier
env:
    node: true
rules:
  no-param-reassign: 0
  import/no-dynamic-require: 0
  global-require: 0
  no-console: 0
  no-not-accumulator-reassign/no-not-accumulator-reassign: [2, ['reduce'], {props: true}]
