sudo: false
language: node_js
node_js:
  - "6"
  - "7"
  - "8"

os:
  - osx

install:
  - npm prune
  - cd skpm-builder && npm prune && npm install && cd ..
  - cd skpm-utils && npm prune && npm install && cd ..
  - npm install

cache:
  directories:
    - node_modules
    - skpm-builder/node_modules
    - skpm-utils/node_modules

before_install:
  - npm set progress=false
